# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protofiles/models.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protofiles import m_helmets_pb2 as src_dot_protofiles_dot_m__helmets__pb2
from src.protofiles import m_helmets_f_pb2 as src_dot_protofiles_dot_m__helmets__f__pb2
from src.protofiles import online_pb2 as src_dot_protofiles_dot_online__pb2
from src.protofiles import nxt_thrty_days_pb2 as src_dot_protofiles_dot_nxt__thrty__days__pb2
from src.protofiles import lng_time_no_see_pb2 as src_dot_protofiles_dot_lng__time__no__see__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/protofiles/models.proto',
  package='templates',
  syntax='proto3',
  serialized_pb=_b('\n\x1bsrc/protofiles/models.proto\x12\ttemplates\x1a\x1esrc/protofiles/m_helmets.proto\x1a src/protofiles/m_helmets_f.proto\x1a\x1bsrc/protofiles/online.proto\x1a#src/protofiles/nxt_thrty_days.proto\x1a$src/protofiles/lng_time_no_see.proto\"\xea\x01\n\x07Options\x12\'\n\tm_helmets\x18\x01 \x01(\x0b\x32\x14.templates.M_Helmets\x12+\n\x0bm_helmets_f\x18\x02 \x01(\x0b\x32\x16.templates.M_Helmets_F\x12!\n\x06online\x18\x03 \x01(\x0b\x32\x11.templates.Online\x12\x31\n\x0enxt_thrty_days\x18\x04 \x01(\x0b\x32\x19.templates.Nxt_Thrty_Days\x12\x33\n\x0flng_time_no_see\x18\x05 \x01(\x0b\x32\x1a.templates.Lng_Time_No_See\"-\n\x06Models\x12#\n\x07options\x18\x01 \x03(\x0b\x32\x12.templates.Optionsb\x06proto3')
  ,
  dependencies=[src_dot_protofiles_dot_m__helmets__pb2.DESCRIPTOR,src_dot_protofiles_dot_m__helmets__f__pb2.DESCRIPTOR,src_dot_protofiles_dot_online__pb2.DESCRIPTOR,src_dot_protofiles_dot_nxt__thrty__days__pb2.DESCRIPTOR,src_dot_protofiles_dot_lng__time__no__see__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='templates.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_helmets', full_name='templates.Options.m_helmets', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_helmets_f', full_name='templates.Options.m_helmets_f', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='online', full_name='templates.Options.online', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nxt_thrty_days', full_name='templates.Options.nxt_thrty_days', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lng_time_no_see', full_name='templates.Options.lng_time_no_see', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=447,
)


_MODELS = _descriptor.Descriptor(
  name='Models',
  full_name='templates.Models',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='options', full_name='templates.Models.options', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=494,
)

_OPTIONS.fields_by_name['m_helmets'].message_type = src_dot_protofiles_dot_m__helmets__pb2._M_HELMETS
_OPTIONS.fields_by_name['m_helmets_f'].message_type = src_dot_protofiles_dot_m__helmets__f__pb2._M_HELMETS_F
_OPTIONS.fields_by_name['online'].message_type = src_dot_protofiles_dot_online__pb2._ONLINE
_OPTIONS.fields_by_name['nxt_thrty_days'].message_type = src_dot_protofiles_dot_nxt__thrty__days__pb2._NXT_THRTY_DAYS
_OPTIONS.fields_by_name['lng_time_no_see'].message_type = src_dot_protofiles_dot_lng__time__no__see__pb2._LNG_TIME_NO_SEE
_MODELS.fields_by_name['options'].message_type = _OPTIONS
DESCRIPTOR.message_types_by_name['Options'] = _OPTIONS
DESCRIPTOR.message_types_by_name['Models'] = _MODELS

Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), dict(
  DESCRIPTOR = _OPTIONS,
  __module__ = 'src.protofiles.models_pb2'
  # @@protoc_insertion_point(class_scope:templates.Options)
  ))
_sym_db.RegisterMessage(Options)

Models = _reflection.GeneratedProtocolMessageType('Models', (_message.Message,), dict(
  DESCRIPTOR = _MODELS,
  __module__ = 'src.protofiles.models_pb2'
  # @@protoc_insertion_point(class_scope:templates.Models)
  ))
_sym_db.RegisterMessage(Models)


# @@protoc_insertion_point(module_scope)
